### ISSUE TITLE
TextNow log 

### ISSUE THREAD

**Issue by perfectlyimaginary** [atom/teletype-server#54]
#
[textnow (1).log](https://github.com/atom/teletype-server/files/4003945/textnow.1.log)

**Comment by Arcanemagus** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us halfway :grinning:
